apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapplication
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/helm-example
    repoURL: 'https://github.com/abhishakeonteddu/gitopps_repo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
