apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knativeserv_demo
spec:
  destination:
    name: ''
    namespace: knative-demp
    server: 'https://kubernetes.default.svc'
  source:
    path: /
    repoURL: 'https://github.com/abhishakeonteddu/knative_serv_demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
